# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run at UTC time
on:
  schedule:
    - cron: "40 5 * * *"
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Run script
        run: npm run request

      - name: Configure Git
        run: |
          git config --global user.email "1348746268@qq.com"
          git config --global user.name "tengjiang"

      # Runs a set of commands using the runners shell
      - name: Commit and push changes
        shell: bash
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto commit"
            git remote set-url origin https://${github.actor}:${{secrets.DEPLOY_KEY}}@github.com/${{github.repository}}.git
            git push origin ${{ github.ref }}
          fi
