# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run at UTC time
on:
  schedule:
    - cron: "50 6 * * *"
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Run script
        run: npm run request

      - name: Configure Git
        run: |
          git config --global user.email "1348746268@qq.com"
          git config --global user.name "jiangteng"

      # Runs a set of commands using the runners shell
      - name: Commit
        shell: bash
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto commit"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
